# Generated by PSDK Battle Animation Creator — 2026-08-02
# Attack: :sundersound  |  Usage: :first_use
ya = Yuki::Animation

# ── animation_user ────────────────────────────────────────────────
create_ring = ya.create_sprite(:viewport, :ring, Sprite, nil,
    [:load, 'circle-xl', :animation],
    [:opacity=, 255],
    [:zoom=, 0],
    [:set_origin, 32, 32]
  )

animation_user = ya.player(
  create_ring,
  ya.resolved(
    ya.tone_animation(0.03, :ring, [0.6157, 0.0314, 0.8314, 0], [0.6157, 0.0314, 0.8314, 1]),
    ya.particle_on_sprite(0.02000000000000001, :ring, :user, 1, 1),
    ya.wait(0.05),
    ya.parallel(
      ya.particle_move_to_sprite(0.8, :ring, :user, :target, 1, 1),
      ya.particle_zoom(0.8, :ring, :user, 0.3, 1.5),
      ya.player(
        ya.wait(0.4),
        ya.opacity_change(0.4, :ring, 255, 0)
      )
    )
  ),
  ya.dispose_sprite(:ring)
)

# ── animation_target ──────────────────────────────────────────────
animation_target = ya.wait(0)

# ── Registration ──────────────────────────────────────────────────
Battle::MoveAnimation.register_specific_animation(:sundersound, :first_use, animation_user, animation_target)